### PR TITLE
Safely handle EOFError on a IO#readpartial

### PR DESCRIPTION
**Pull request by xmjw**
We've been using Krakow for a few months now, and it's fabulous. You're all awesome.

We have experienced occasional errors however, and I think it's a slightly peculiarity of the implementation: (ellipsis for readability)

```
Actor crashed! 
EOFError: end of file reached 
  /app/vendor/bundle/ruby/2.1.0/gems/krakow-0.4.2/lib/krakow/ksocket.rb:55:in `readpartial' 
  .../krakow-0.4.2/lib/krakow/ksocket.rb:55:in `block (2 levels) in read_loop' 
  .../krakow-0.4.2/lib/krakow/ksocket.rb:95:in `socket' 
  .../krakow-0.4.2/lib/krakow/ksocket.rb:55:in `block in read_loop' 
  .../celluloid-0.16.0/lib/celluloid/calls.rb:26:in `call' 
  .../celluloid-0.16.0/lib/celluloid/calls.rb:26:in `public_send' 
  .../celluloid-0.16.0/lib/celluloid/calls.rb:26:in `dispatch' 
  .../celluloid-0.16.0/lib/celluloid/calls.rb:63:in `dispatch' 
  .../celluloid-0.16.0/lib/celluloid/future.rb:14:in `block in new' 
  .../celluloid-0.16.0/lib/celluloid/thread_handle.rb:13:in `block in initialize' 
  .../celluloid-0.16.0/lib/celluloid/actor_system.rb:32:in `block in get_thread' 
  .../celluloid-0.16.0/lib/celluloid/internal_pool.rb:130:in `call' 
  .../celluloid-0.16.0/lib/celluloid/internal_pool.rb:130:in `block in create' 
  (celluloid):0:in `remote procedure call' 
  .../celluloid-0.16.0/lib/celluloid/future.rb:104:in `value' 
  .../celluloid-0.16.0/lib/celluloid/future.rb:68:in `value' 
  .../celluloid-0.16.0/lib/celluloid.rb:439:in `defer' 
  .../krakow-0.4.2/lib/krakow/ksocket.rb:53:in `read_loop' 
  .../celluloid-0.16.0/lib/celluloid/calls.rb:26:in `public_send' 
  .../celluloid-0.16.0/lib/celluloid/calls.rb:26:in `dispatch' 
  .../celluloid-0.16.0/lib/celluloid/calls.rb:122:in `dispatch'  
  .../celluloid-0.16.0/lib/celluloid/cell.rb:60:in `block in invoke' 
  .../celluloid-0.16.0/lib/celluloid/cell.rb:71:in `block in task' 
  .../celluloid-0.16.0/lib/celluloid/actor.rb:357:in `block in task' 
  .../celluloid-0.16.0/lib/celluloid/tasks.rb:57:in `block in initialize' 
  .../celluloid-0.16.0/lib/celluloid/tasks/task_fiber.rb:15:in `block in create' 
```

I've spent some time digging, and this seems to be because the `IO#readpartial` legitimately raises an `EOFError` when there is [nothing to read](http://ruby-doc.org/core-2.2.2/IO.html#method-i-readpartial). Because this isn't handled, an EOF on a socket causes the whole system to crash. Weirdly, this is only an issue with _some_ of the services we're running with Krakow, but this should make the whole thing a little more stable.

Apologies if this is completely the wrong way to go with this, but I wanted to open with some code rather than just open an issue and hope someone else will fix it! Let me know what you think.

### CODE REVIEW

**Comment by mreiferson** [comment]
@xmjw reading those docs, it seems like the `EOF` error that's thrown is real and probably shouldn't be _swallowed_ (it might need to be handled _differently_ though).

**Comment by xmjw** [comment]
Sure thing @mreiferson. So I'm wondering if we should somehow get this to cause a socket connection to reset. But if we let it raise it'll go to Celluloid and bring the application down.

Beyond adding some logging out on this, I'm not really sure what else can be done. 

I think it's fair to say this shouldn't cause a crash, but I know very little about Celluloid and Krakow, so if you've any guidance on how to deal with this, I'm happy to go hack around and figure out a better solution? Otherwise I'lll just keep tinkering until I get something that seems reasonable...

Ta.

**Comment by mreiferson** [comment]
gonna defer to @chrisroberts for Krakow/Celluloid specifics, but I _definitely_ think Krakow should handle this more gracefully... not by ignoring, but by closing/cleaning up the connection and propagating that event like any other connection failure.

**Comment by xmjw** [comment]
@mreiferson  Yes, I'd come to the same conclusion. But I'm still a bit fuzzy on getting it to work, so tips from @chrisroberts appreciated. Per my original stack trace we seem to drop out of `KSocket` into Celluloid. I'm _guessing_ there is a type of error we can wrap this in, then `raise` it such that Celluloid will not blow up (although total failure only happens some of the time for us), and the socket can be dealt with accordingly.

I'll keep looking down this path to see if I can figure it out.

**Comment by xmjw** [comment]
Hm. So I'm going to close this out. We found another way of dealing with it. We were using Consul and HA Proxy to get to our NSQD nodes, which was clearly a mistake, because one of those things closes the connection, and causes the socket to die. I think this can still be handled better, but I'm not really sure where to go with it. Appreciate the help.

**Pull request closed without merging**
